const items=[{id:"shirts",name:"Shirts"},{id:"pants",name:"Pants"},{id:"tshirts",name:"T-Shirts"},{id:"shorts",name:"Shorts"},{id:"trackpants",name:"Track Pants"},{id:"bedsheets",name:"Bedsheets"},{id:"towels",name:"Towels"},{id:"pillowcovers",name:"Pillow Covers"},{id:"underwear",name:"Underwear"},{id:"innertopwear",name:"Inner Top Wear"}];
const q=Object.fromEntries(items.map(x=>[x.id,0])), $=x=>document.getElementById(x);
function render(){itemsGrid.innerHTML=items.map(x=>`<div class="item" id="card-${x.id}"><span class="item-name">${x.name}</span><div class="controls"><button class="qty" data-id="${x.id}" data-change="-1">−</button><span class="num" id="num-${x.id}">0</span><button class="qty" data-id="${x.id}" data-change="1">+</button></div></div>`).join("")}
function total(){return Object.values(q).reduce((a,b)=>a+b,0)}
itemsGrid.addEventListener("click",e=>{const b=e.target.closest(".qty");if(!b)return;const id=b.dataset.id,n=Math.max(0,Math.min(99,q[id]+Number(b.dataset.change)));if(n===q[id])return;q[id]=n;$("num-"+id).textContent=n;$("liveTotal").textContent=total();const c=$("card-"+id);c.classList.remove("bump");void c.offsetWidth;c.classList.add("bump")});
function rid(){const d=new Date(),s=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;return`LD-${s}-${Math.floor(1000+Math.random()*9000)}`}
submitBtn.onclick=()=>{if(!total()){error.textContent="Please select at least one item first.";return}error.textContent="";const d=new Date();receiptNumber.textContent=rid();receiptDate.textContent=d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});receiptTime.textContent=d.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:true});totalItems.textContent=total();receiptItems.innerHTML=items.filter(x=>q[x.id]>0).map(x=>`<div class="row"><span>${x.name}</span><span>${q[x.id]}</span></div>`).join("");downloadMsg.textContent="";formScreen.classList.remove("active");receiptScreen.classList.add("active");scrollTo({top:0,behavior:"smooth"})};
function loadCanvas(){return new Promise((ok,no)=>{const s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js";s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
downloadBtn.onclick=async()=>{downloadMsg.textContent="Preparing your receipt…";downloadBtn.disabled=true;try{if(typeof html2canvas==="undefined")await loadCanvas();const canvas=await html2canvas(receiptCapture,{backgroundColor:"#fff",scale:3,useCORS:true,logging:false});canvas.toBlob(blob=>{if(!blob)throw Error();const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`Laundry-Receipt-${receiptNumber.textContent}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);downloadMsg.textContent="Receipt downloaded ✓";downloadBtn.disabled=false},"image/png")}catch(e){downloadMsg.textContent="Download failed. Please try again.";downloadBtn.disabled=false}};
newBtn.onclick=()=>{items.forEach(x=>{q[x.id]=0;$("num-"+x.id).textContent="0"});$("liveTotal").textContent="0";error.textContent="";downloadMsg.textContent="";receiptScreen.classList.remove("active");formScreen.classList.add("active");scrollTo({top:0,behavior:"smooth"})};
render();